# Generated by Django 5.1.1 on 2024-09-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='products_provided',
        ),
    ]
