# Generated by Django 5.1.1 on 2024-09-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
