# Generated by Django 5.1.1 on 2024-10-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role_unique_together_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_conditions',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
